#!/usr/bin/with-contenv sh

# clean up extensions
for i in ldap duo header cas openid quickconnect totp
do
  rm -rvf ${GUACAMOLE_HOME}/extensions/guacamole-auth-${i}-${GUACAMOLE_VERSION}.jar
done

# enable extensions
while IFS= read -r line
do
  for i in ldap duo header cas openid quickconnect totp
  do
    if [ "$line" = "*${i}-*" ]
    then
      cp -nv ${GUACAMOLE_HOME}/extensions-available/guacamole-auth-${i}-${GUACAMOLE_VERSION}.jar ${GUACAMOLE_HOME}/extensions
    fi
  done
done < /data/guacamole/guacamole.properties
