#!/usr/bin/with-contenv sh

# clean up extensions
for i in ldap duo header cas openid quickconnect totp
do
  rm -rvf /data/guacamole/extensions/guacamole-auth-${i}-${GUAC_VER}.jar
done

# enable extensions
while IFS= read -r line
do
  for i in ldap duo header cas openid quickconnect totp
  do
    if [ "$line" = *"${i}-"* ]
    then
      cp -nv /data/guacamole/extensions-available/guacamole-auth-${i}-${GUAC_VER}.jar /data/guacamole/extensions
    fi
  done
done < /data/guacamole/guacamole.properties
